/**
 * Tests for the sales-import upgrades: refund netting, provider
 * detection, confidence scoring, and the Excel guidance message.
 *
 * Run with:  npx tsx lib/__tests__/importUpgrades.test.ts
 */
import * as fs from 'fs';
import * as path from 'path';

interface Test { name: string; pass: boolean; detail: string }
const results: Test[] = [];
function expect(name: string, cond: boolean, detail: string = '') {
  results.push({ name, pass: cond, detail });
}

import { parseCSVSalesReport } from '../parsers/csvSales';
import { detectProvider, computeImportConfidence } from '../parsers/providerDetect';

// ── 1. Refund netting in the CSV parser ──────────────────────────────────────
{
  const csv = [
    'Item,Qty,Net Sales',
    'Flat White,10,35.00',
    'Flat White,-2,-7.00',   // refund row
    'Croissant,5,14.00',
  ].join('\n');
  const r = parseCSVSalesReport(csv);
  const fw = r.lines.find(l => l.product_name === 'Flat White')!;
  expect('refund_nets_quantity', fw.quantity === 8, `qty=${fw.quantity}`);
  expect('refund_nets_total', Math.abs(fw.line_total - 28) < 0.001, `total=${fw.line_total}`);
  expect('refund_rows_counted', r.diagnostics?.refundRowCount === 1,
    `refundRowCount=${r.diagnostics?.refundRowCount}`);
  expect('other_products_untouched',
    r.lines.find(l => l.product_name === 'Croissant')?.line_total === 14, '');
}
{
  // Fully refunded product nets to zero → dropped, not stored as negative.
  const csv = [
    'Item,Qty,Total',
    'Latte,3,10.50',
    'Latte,-3,-10.50',
  ].join('\n');
  const r = parseCSVSalesReport(csv);
  expect('fully_refunded_product_dropped',
    !r.lines.some(l => l.product_name === 'Latte'),
    r.lines.map(l => l.product_name).join(','));
  expect('net_negative_skip_reason_recorded',
    (r.diagnostics?.skipReasons['net_negative_after_refunds'] ?? 0) === 1,
    JSON.stringify(r.diagnostics?.skipReasons));
}
{
  // Accountancy-style parenthesised negative still works.
  const csv = [
    'Item,Qty,Total',
    'Mocha,4,15.20',
    'Mocha,1,(3.80)',
  ].join('\n');
  const r = parseCSVSalesReport(csv);
  const mocha = r.lines.find(l => l.product_name === 'Mocha')!;
  expect('parenthesised_negative_nets', Math.abs(mocha.line_total - 11.4) < 0.001,
    `total=${mocha.line_total}`);
}
{
  // No refunds → counter stays 0 and nothing changes.
  const csv = 'Item,Qty,Total\nTea,2,5.00';
  const r = parseCSVSalesReport(csv);
  expect('no_refunds_counter_zero', r.diagnostics?.refundRowCount === 0,
    `refundRowCount=${r.diagnostics?.refundRowCount}`);
}

// ── 2. Provider detection ─────────────────────────────────────────────────────
expect('detects_square', detectProvider('square-sales-2026-06.csv') === 'Square', '');
expect('detects_sumup', detectProvider('Report generated by SumUp') === 'SumUp', '');
expect('detects_zettle', detectProvider('iZettle daily takings') === 'Zettle', '');
expect('detects_eposnow', detectProvider('Epos Now product sales') === 'Epos Now', '');
expect('detects_loyverse', detectProvider(null, 'Loyverse POS export') === 'Loyverse', '');
expect('unknown_returns_null', detectProvider('items-sold-june.csv', 'Item,Qty,Total') === null, '');
expect('empty_returns_null', detectProvider('', null, undefined) === null, '');
expect('generic_word_toast_not_matched',
  detectProvider('Toasted Sandwich,3,12.00') === null,
  'the food word "toast(ed)" must not read as the Toast POS brand');

// ── 3. Confidence scoring ─────────────────────────────────────────────────────
expect('high_confidence_clean_csv',
  computeImportConfidence({ acceptedRows: 12, skippedRows: 0, coveragePercent: 90, sourceFormat: 'csv' }) === 'high', '');
expect('low_confidence_single_row',
  computeImportConfidence({ acceptedRows: 1, skippedRows: 0, coveragePercent: 100, sourceFormat: 'csv' }) === 'low', '');
expect('low_confidence_zero_rows',
  computeImportConfidence({ acceptedRows: 0, skippedRows: 5, coveragePercent: 0, sourceFormat: 'pdf' }) === 'low', '');
expect('low_confidence_heavy_skips',
  computeImportConfidence({ acceptedRows: 4, skippedRows: 10, coveragePercent: 80, sourceFormat: 'csv' }) === 'low', '');
expect('medium_confidence_poor_coverage',
  computeImportConfidence({ acceptedRows: 8, skippedRows: 0, coveragePercent: 40, sourceFormat: 'csv' }) === 'medium', '');
expect('pdf_stricter_than_csv',
  computeImportConfidence({ acceptedRows: 3, skippedRows: 0, coveragePercent: 90, sourceFormat: 'pdf' }) === 'medium'
  && computeImportConfidence({ acceptedRows: 3, skippedRows: 0, coveragePercent: 90, sourceFormat: 'csv' }) === 'high',
  '3 rows is high for CSV but only medium for PDF');

// ── 4. File-content invariants ────────────────────────────────────────────────
const ROOT = path.join(__dirname, '..', '..');
const read = (rel: string) => fs.readFileSync(path.join(ROOT, rel), 'utf8');

const mutationSrc = read('lib/mutations/salesReports.ts');
const modalSrc    = read('components/cogs/ImportReviewModal.tsx');
const pdfSrc      = read('lib/parsers/pdfSales.ts');
const csvSrc      = read('lib/parsers/csvSales.ts');

expect('mutation_has_excel_guidance',
  mutationSrc.includes(".xlsx'") && mutationSrc.includes('Save As'),
  'Excel files must get a clear export-as-CSV message, not a generic error');

expect('excel_check_by_extension_only',
  mutationSrc.includes('iOS mislabels') && mutationSrc.includes('EXTENSION only'),
  'must not treat application/vnd.ms-excel MIME as Excel — iOS uses it for CSVs');

expect('mutation_computes_confidence',
  mutationSrc.includes('computeImportConfidence'),
  'parse mutation must attach a confidence level');

expect('mutation_detects_provider',
  mutationSrc.includes('detectProvider'),
  'parse mutation must attach best-effort provider');

expect('csv_refund_warning_surfaced',
  mutationSrc.includes('netted against sales'),
  'refund netting must be disclosed as a review warning');

expect('modal_shows_provider',
  modalSrc.includes('pending.provider'),
  'review modal must show the detected provider');

expect('modal_shows_confidence',
  modalSrc.includes('pending.confidence'),
  'review modal must show the confidence level');

expect('pdf_parser_detects_provider_internally',
  pdfSrc.includes('detectProvider(') && pdfSrc.includes('provider,'),
  'PDF provider detection happens inside the parser so raw text never leaves it');

expect('csv_no_abs_refund_inflation',
  !csvSrc.includes('Math.abs(lineTotal)'),
  'the abs() that counted refunds as revenue must stay gone');

// ── Report ────────────────────────────────────────────────────────────────────
const passed = results.filter(r => r.pass).length;
const failed = results.filter(r => !r.pass);
const width = Math.max(...results.map(r => r.name.length));
for (const r of results) {
  console.log(`${r.pass ? 'PASS' : 'FAIL'}  ${r.name.padEnd(width + 2)}${r.detail ? ' ' + r.detail : ''}`);
}
console.log(`\n${passed} passed, ${failed.length} failed`);
if (failed.length > 0) process.exit(1);
